# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-27 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import escuelas.models.perfil


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'areas',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cargos',
                'verbose_name_plural': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='CargoEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cargosEscolares',
                'verbose_name_plural': 'cargosEscolares',
            },
        ),
        migrations.CreateModel(
            name='ComentarioDeTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeAlta', models.DateField(blank=True, default=None, null=True)),
                ('comentario', models.TextField(blank=True, default=None, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'comentariosDeTareas',
                'verbose_name_plural': 'comentariosDetareas',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono_particular', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('telefono_celular', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('horario', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('cargo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='escuelas.CargoEscolar')),
            ],
            options={
                'db_table': 'contactos',
                'verbose_name_plural': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contratos',
                'verbose_name_plural': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('esCabecera', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'distritos',
                'verbose_name_plural': 'distritos',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.CharField(db_index=True, max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('latitud', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('longitud', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Area')),
            ],
            options={
                'db_table': 'escuelas',
                'verbose_name_plural': 'escuelas',
            },
        ),
        migrations.CreateModel(
            name='EstadoDeTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estadosDeTarea',
                'verbose_name_plural': 'estadosDeTarea',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('fecha', models.DateField(default=b'2017-01-10')),
                ('inicio', models.TimeField(default=b'00:00:00')),
                ('fin', models.TimeField(default=b'00:00:00')),
                ('todoElDia', models.BooleanField(default=False)),
                ('escuela', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='escuelas.Escuela')),
            ],
            options={
                'db_table': 'eventos',
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'experiencias',
                'verbose_name_plural': 'experiencias',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('distrito', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='escuelas.Distrito')),
            ],
            options={
                'db_table': 'localidades',
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='MotivoDeTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'motivosDeTarea',
                'verbose_name_plural': 'motivosDeTarea',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'niveles',
                'verbose_name_plural': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=escuelas.models.perfil.upload_to, verbose_name=b'image')),
                ('nombre', models.CharField(default=b'', max_length=200)),
                ('apellido', models.CharField(default=b'', max_length=200)),
                ('fechadenacimiento', models.DateField(blank=True, default=None, null=True)),
                ('titulo', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('dni', models.CharField(default=b'0000', max_length=200)),
                ('cuit', models.CharField(default=b'0000', max_length=200)),
                ('cbu', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('direccionCalle', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('direccionAltura', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('direccionPiso', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('direccionDepto', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('direccionTorre', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('codigoPostal', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('telefonoCelular', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('telefonoAlternativo', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('expediente', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('fechaDeIngreso', models.DateField(default=b'2010-10-10')),
                ('fechaDeRenuncia', models.DateField(blank=True, default=None, null=True)),
                ('emailLaboral', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('cargo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='escuelas.Cargo')),
                ('contrato', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='escuelas.Contrato')),
                ('experiencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='escuelas.Experiencia')),
                ('grupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='auth.Group')),
                ('localidad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='escuelas.Localidad')),
            ],
            options={
                'db_table': 'perfiles',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(max_length=255)),
                ('serie', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ups', models.BooleanField(default=False)),
                ('rack', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('llave', models.FileField(blank=True, null=True, upload_to=b'piso_llave_servidor/')),
            ],
            options={
                'db_table': 'pisos',
                'verbose_name_plural': 'pisos',
            },
        ),
        migrations.CreateModel(
            name='PrioridadDeTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prioridadesDeTarea',
                'verbose_name_plural': 'prioridadesDeTarea',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'programas',
                'verbose_name_plural': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'regiones',
                'verbose_name_plural': 'regiones',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket_original', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('fechaDeAlta', models.DateField(blank=True, default=None, null=True)),
                ('descripcion', models.TextField(max_length=1024)),
                ('autor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_autor', to='escuelas.Perfil')),
                ('escuela', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='escuelas.Escuela')),
                ('estadoDeTarea', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='escuelas.EstadoDeTarea')),
                ('motivoDeTarea', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='escuelas.MotivoDeTarea')),
                ('prioridadDeTarea', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='escuelas.PrioridadDeTarea')),
                ('responsable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_responsable', to='escuelas.Perfil')),
            ],
            options={
                'db_table': 'tareas',
                'verbose_name_plural': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='TipoDeFinanciamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tiposDeFinanciamiento',
                'verbose_name_plural': 'tiposDeFinanciamiento',
            },
        ),
        migrations.CreateModel(
            name='TipoDeGestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tiposDeGestion',
                'verbose_name_plural': 'tiposDeGestion',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='escuelas.Region'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='responsable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='escuelas.Perfil'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='localidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Localidad'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='nivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Nivel'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='piso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Piso'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='programas',
            field=models.ManyToManyField(related_name='escuelas', to='escuelas.Programa'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='tipoDeFinanciamiento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.TipoDeFinanciamiento'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='tipoDeGestion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.TipoDeGestion'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='escuelas.Region'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='escuela',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='escuelas.Escuela'),
        ),
        migrations.AddField(
            model_name='comentariodetarea',
            name='autor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea_autor', to='escuelas.Perfil'),
        ),
        migrations.AddField(
            model_name='comentariodetarea',
            name='tarea',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea', to='escuelas.Tarea'),
        ),
    ]
