# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariodetarea',
            name='comentario',
            field=models.TextField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='comentariodetarea',
            name='tarea',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosDeTarea', to='escuelas.Tarea'),
        ),
    ]
