# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_auto_20170103_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
