# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_evento_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(default=b'2017-01-10'),
        ),
    ]
