# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0004_evento_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='acompaniantes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='eventos_acompaniantes', to='escuelas.Perfil'),
        ),
    ]
