# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0004_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=200)),
                ('fechadenacimiento', models.DateField()),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
    ]
