# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0005_evento_acompaniantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='acompaniantes',
            field=models.ManyToManyField(blank=True, default=None, related_name='eventos_acompaniantes', to='escuelas.Perfil'),
        ),
    ]
