# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0005_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'municipios',
                'verbose_name_plural': 'municipios',
            },
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterModelOptions(
            name='escuela',
            options={'verbose_name_plural': 'escuelas'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name_plural': 'eventos'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'regiones'},
        ),
        migrations.AddField(
            model_name='municipio',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.Region'),
        ),
    ]
