# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0006_auto_20170305_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='esCabecera',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='escuelas.Region'),
        ),
    ]
