# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0007_categoriadeevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='eventos',
            field=models.ManyToManyField(related_name='evntos_perfiles', to='escuelas.Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='responsable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_responsable', to='escuelas.Perfil'),
        ),
    ]
