# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0007_auto_20170306_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
