# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0008_auto_20170804_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='eventos',
        ),
        migrations.AlterField(
            model_name='evento',
            name='responsable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='escuelas.Perfil'),
        ),
    ]
