# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0009_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fechaDeIngreso',
            field=models.DateField(default=b'2010-10-10'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cuit',
            field=models.CharField(default=b'0000', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(default=b'0000', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechadenacimiento',
            field=models.DateField(default=b'2010-10-10'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
