# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0010_estadodevalidacion_validacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacion',
            name='legacy_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
