# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import escuelas.models.perfil


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0010_auto_20170307_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=escuelas.models.perfil.upload_to, verbose_name=b'image'),
        ),
    ]
