# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0011_perfil_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='director',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='telefono',
        ),
    ]
