# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0011_auto_20170804_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='fechaConformacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuelas.Escuela'),
        ),
    ]
