# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-07 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0012_auto_20170807_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDeConformacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'motivosDeConformacion',
                'verbose_name_plural': 'motivosDeConformacion',
            },
        ),
        migrations.AddField(
            model_name='escuela',
            name='motivoDeConformacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.MotivoDeConformacion'),
        ),
    ]
