# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-08 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0013_auto_20170807_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuela',
            old_name='parent_id',
            new_name='padre',
        ),
    ]
