# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-09 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0014_auto_20170808_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioDeValidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=None, null=True)),
                ('comentario', models.TextField(blank=True, default=None, max_length=4096, null=True)),
                ('cantidad', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('autor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosDeValidacion', to='escuelas.Perfil')),
                ('validacion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosDeValidacion', to='escuelas.Validacion')),
            ],
            options={
                'db_table': 'comentariosDeValidacion',
                'verbose_name_plural': 'comentariosDeValidacion',
            },
        ),
    ]
