# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0015_comentariodevalidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariodevalidacion',
            name='legacy_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
