# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0017_auto_20170809_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.BooleanField(default=1),
        ),
    ]
