# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0018_distrito_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='esCabecera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distrito',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='escuelas.Region'),
        ),
    ]
