# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0019_auto_20170609_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='region',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
