# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0020_auto_20170816_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='conformada',
            field=models.BooleanField(default=False),
        ),
    ]
