# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0020_auto_20170609_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Area'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='latitud',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='localidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Localidad'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='longitud',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='nivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Nivel'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='programa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Programa'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='tipoDeFinanciamiento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.TipoDeFinanciamiento'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='tipoDeGestion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.TipoDeGestion'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='distrito',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='escuelas.Distrito'),
        ),
    ]
