# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0021_auto_20170609_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='programa',
        ),
        migrations.AddField(
            model_name='escuela',
            name='programas',
            field=models.ManyToManyField(related_name='escuelas', to='escuelas.Programa'),
        ),
    ]
