# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0022_piso_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='servidor',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
