# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0023_auto_20170817_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDePaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estadosDePaquete',
                'verbose_name_plural': 'estadosDePaquete',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, default=None, null=True)),
                ('fechaPedido', models.DateField(blank=True, default=None, null=True)),
                ('ne', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('idHardware', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('marcaDeArranque', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('comentario', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('carpetaPaquete', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('fechaEnvio', models.DateField(blank=True, default=None, null=True)),
                ('zipPaquete', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('fechaDevolucion', models.DateField(blank=True, default=None, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('escuela', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='escuelas.Escuela')),
                ('estado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='escuelas.EstadoDePaquete')),
            ],
            options={
                'db_table': 'paquetes',
                'verbose_name_plural': 'paquetes',
            },
        ),
    ]
