# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0023_auto_20170616_1437'),
        ('escuelas', '0023_auto_20170616_1511'),
    ]

    operations = [
    ]
