# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0025_auto_20170820_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariodetarea',
            old_name='fechaDeAlta',
            new_name='fecha_de_alta',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='estadoDeTarea',
            new_name='estado_de_tarea',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='fechaDeAlta',
            new_name='fecha_de_alta',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='motivoDeTarea',
            new_name='motivo_de_tarea',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='prioridadDeTarea',
            new_name='prioridad_de_tarea',
        ),
    ]
