# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0025_auto_20170616_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emailLaboral',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='expediente',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fechaDeReuncia',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='programa',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='escuelas.Region'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefonoAlternativo',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefonoCelular',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
