# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0026_auto_20170616_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='codigoPosal',
            new_name='codigoPostal',
        ),
    ]
