# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0026_auto_20170825_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='id_ticket_original',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
