# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0027_auto_20170825_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modalidades',
                'verbose_name_plural': 'modalidades',
            },
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ('-fecha_de_alta',), 'verbose_name_plural': 'tareas'},
        ),
        migrations.AddField(
            model_name='escuela',
            name='modalidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Modalidad'),
        ),
    ]
