# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0028_auto_20170622_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='latitud',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='longitud',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
