# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0028_auto_20170825_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuela',
            old_name='fechaConformacion',
            new_name='fecha_conformacion',
        ),
        migrations.RenameField(
            model_name='escuela',
            old_name='motivoDeConformacion',
            new_name='motivo_de_conformacion',
        ),
        migrations.RenameField(
            model_name='escuela',
            old_name='tipoDeFinanciamiento',
            new_name='tipo_de_financiamiento',
        ),
        migrations.RenameField(
            model_name='escuela',
            old_name='tipoDeGestion',
            new_name='tipo_de_gestion',
        ),
    ]
