# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0029_auto_20170825_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='escuelas.CategoriaDeEvento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='resumen',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
