# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0029_auto_20170623_1246'),
        ('escuelas', '0030_auto_20170623_1239'),
    ]

    operations = [
    ]
