# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0030_auto_20170829_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='acta_legacy',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='minuta',
            field=models.TextField(blank=True, default=None, max_length=4096, null=True),
        ),
    ]
