# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-06 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0031_auto_20170830_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='cantidadDeParticipantes',
            new_name='cantidad_de_participantes',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='requiereTraslado',
            new_name='requiere_traslado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='todoElDia',
        ),
    ]
