# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0031_merge_20170623_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='descripcion',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
