# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-11 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0032_auto_20170906_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='carpetaPaquete',
            new_name='carpeta_paquete',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='fechaDevolucion',
            new_name='fecha_devolucion',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='fechaEnvio',
            new_name='fecha_envio',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='fechaPedido',
            new_name='fecha_pedido',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='idHardware',
            new_name='id_hardware',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='marcaDeArranque',
            new_name='marca_de_arranque',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='zipPaquete',
            new_name='zip_paquete',
        ),
    ]
