# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0032_cargo_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=255)),
                ('ups', models.BooleanField()),
                ('rack', models.BooleanField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'pisos',
                'verbose_name_plural': 'pisos',
            },
        ),
        migrations.AddField(
            model_name='escuela',
            name='piso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuelas.Piso'),
        ),
    ]
