# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0033_auto_20170911_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='acta',
            field=models.FileField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
