# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0033_auto_20170623_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cargosEscolares',
                'verbose_name_plural': 'cargosEscolares',
            },
        ),
    ]
