# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0034_cargoescolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='escuelas.CargoEscolar'),
        ),
    ]
