# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0036_auto_20170919_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validacion',
            old_name='cantidad',
            new_name='cantidad_pedidas',
        ),
        migrations.RenameField(
            model_name='validacion',
            old_name='fechaDeAlta',
            new_name='fecha_de_alta',
        ),
        migrations.AddField(
            model_name='validacion',
            name='cantidad_validadas',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
