# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0036_auto_20170630_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='horario',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono_celular',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono_particular',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
