# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-02 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0037_auto_20170630_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Contrato',
            new_name='contrato',
        ),
        migrations.AlterField(
            model_name='piso',
            name='serie',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
