# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-20 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0037_auto_20170920_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validacion',
            options={'ordering': ('-fecha_de_alta',), 'verbose_name_plural': 'validaciones'},
        ),
    ]
