# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0038_auto_20170702_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piso',
            name='rack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piso',
            name='ups',
            field=models.BooleanField(default=False),
        ),
    ]
