# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0038_auto_20170920_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='piso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuela', to='escuelas.Piso'),
        ),
    ]
