# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-04 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0039_auto_20170703_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='horario',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono_celular',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono_particular',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
