# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-12 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0040_auto_20170704_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estadosDeTareas',
                'verbose_name_plural': 'estadosDeTareas',
            },
        ),
        migrations.CreateModel(
            name='MotivoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'motivosDeTareas',
                'verbose_name_plural': 'motivosDeTareas',
            },
        ),
        migrations.CreateModel(
            name='PrioridadTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prioridades',
                'verbose_name_plural': 'prioridades',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket_original', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1024)),
                ('escuela', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='escuelas.Escuela')),
                ('estado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='escuelas.EstadoTarea')),
                ('motivo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='escuelas.MotivoTarea')),
                ('prioridad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='escuelas.PrioridadTarea')),
            ],
            options={
                'db_table': 'tareas',
                'verbose_name_plural': 'tareas',
            },
        ),
    ]
