# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-26 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0040_auto_20170922_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='id_devolucion',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
