# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('escuelas', '0041_estadotarea_motivotarea_prioridadtarea_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='grupo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='auth.Group'),
        ),
    ]
