# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0042_perfil_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='fechaDeReuncia',
            new_name='fechaDeRenuncia',
        ),
    ]
