# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-19 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0043_auto_20171011_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacion',
            name='fecha_de_modificacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
