# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0043_auto_20170713_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fechadenacimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
