# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0044_auto_20170713_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='autor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_autor', to='escuelas.Perfil'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechaDeAlta',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_responsable', to='escuelas.Perfil'),
        ),
    ]
