# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0046_auto_20170714_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fechafin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fechainicio',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(default=b'2017-01-10'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fin',
            field=models.TimeField(default=b'00:00:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inicio',
            field=models.TimeField(default=b'00:00:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='responsable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='escuelas.Perfil'),
        ),
    ]
