# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0046_escuela_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='tipo_de_financiamiento',
            field=models.ManyToManyField(blank=True, default=None, related_name='escuelas', to='escuelas.TipoDeFinanciamiento'),
        ),
    ]
