# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0047_auto_20171209_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('trabajo_id', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=256)),
                ('detalle', models.TextField(blank=True, default='', max_length=2048, null=True)),
                ('archivo', models.FileField(blank=True, default=None, null=True, upload_to=b'')),
                ('resultado', models.TextField(blank=True, default=None, max_length=512, null=True)),
                ('progreso', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
