# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0047_auto_20170716_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeAlta', models.DateField(blank=True, default=None, null=True)),
                ('comentario', models.CharField(max_length=1024)),
                ('autor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea_autor', to='escuelas.Perfil')),
                ('id_ticket_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea', to='escuelas.Tarea')),
            ],
            options={
                'db_table': 'comentariosDeTareas',
                'verbose_name_plural': 'comentariosDetareas',
            },
        ),
    ]
