# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-18 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0048_comentariotarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariotarea',
            old_name='id_ticket_original',
            new_name='tarea',
        ),
    ]
