# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0049_auto_20170718_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariotarea',
            name='comentario',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(max_length=1024),
        ),
    ]
