# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0049_trabajo_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='ma_hexa',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
