# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0050_auto_20170718_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariotarea',
            name='comentario',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='comentariotarea',
            name='tarea',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea', to='escuelas.Tarea'),
        ),
    ]
