# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-30 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0050_paquete_ma_hexa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionDePaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(blank=True, default=None, null=True, upload_to=b'')),
                ('perfil', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribucion_de_paquetes', to='escuelas.Perfil')),
            ],
            options={
                'ordering': ('-fecha',),
                'db_table': 'distribucion_de_paquete',
                'verbose_name_plural': 'distribucionDePaquetes',
            },
        ),
    ]
