# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0051_auto_20170718_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='escuela',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='escuelas.Escuela'),
        ),
    ]
