# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-08 00:36
from __future__ import unicode_literals
from escuelas.models import Paquete

from django.db import migrations

def corregir_valor_hexa(valor):
    return hex(int(valor, 16))[2:]

def convertir_decimal_a_hexa(valor):
    return hex(int(valor))[2:]

def corregir_paquete(paquete):
    if paquete.ma_hexa:
        paquete.ma_hexa = corregir_valor_hexa(paquete.ma_hexa)
    else:
        if not paquete.tpmdata:
            paquete.ma_hexa = corregir_valor_hexa(paquete.marca_de_arranque)
        else:
            paquete.ma_hexa = convertir_decimal_a_hexa(paquete.marca_de_arranque)

    paquete.save()

def corregir_valores_hexa(apps, schema_editor):

    for paquete in Paquete.objects.filter(fecha_pedido__year=2018):
        try:
            corregir_paquete(paquete)
        except (ValueError, TypeError) as error:
            print("Imposible corregir el paquete id={} ma_hexa={} marca_de_arranque={} tpmdata={}".format(paquete.id, paquete.ma_hexa, paquete.marca_de_arranque, paquete.tpmdata))

class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0053_paquete_zip_devolucion'),
    ]

    operations = [
        migrations.RunPython(corregir_valores_hexa, migrations.RunPython.noop),
    ]
