# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-20 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0054_corregir_valores_hexadecimales_con_ceros_a_izquierda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ('apellido',), 'verbose_name_plural': 'perfiles'},
        ),
    ]
