# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0055_auto_20170725_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioridadtarea',
            options={'verbose_name_plural': 'prioridadesDeTareas'},
        ),
        migrations.AlterModelTable(
            name='prioridadtarea',
            table='prioridadesDeTareas',
        ),
    ]
