# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-11 18:24
from __future__ import unicode_literals

from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

from django.db import migrations
from escuelas import models

def crear_permiso(apps, schema_editor):
    TAREAS_ELIMINAR = 'tareas.eliminar'

    modelo, permiso = TAREAS_ELIMINAR.split('.')

    try:
        grupo_administrador = Group.objects.get(name="Administrador")
        
        tipo, _ = ContentType.objects.get_or_create(app_label='escuelas', model=modelo)
        permiso = Permission.objects.create(name=permiso, codename=TAREAS_ELIMINAR, content_type=tipo)

        grupo_administrador.permissions.add(permiso)
    except Group.DoesNotExist:
        print("CUIDADO: no existe el grupo administrador.")


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0055_auto_20180520_0041'),
    ]

    operations = [
        migrations.RunPython(crear_permiso, migrations.RunPython.noop),
    ]
