# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-26 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0056_crear_permiso_para_eliminar_tareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aplicaciones',
                'verbose_name_plural': 'aplicaciones',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='aplicaciones',
            field=models.ManyToManyField(blank=True, default=None, related_name='perfil_aplicaciones', to='escuelas.Aplicacion'),
        ),
    ]
