# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0056_auto_20170725_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadotarea',
            options={'verbose_name_plural': 'estadosDeTarea'},
        ),
        migrations.AlterModelOptions(
            name='motivotarea',
            options={'verbose_name_plural': 'motivosDeTarea'},
        ),
        migrations.AlterModelOptions(
            name='prioridadtarea',
            options={'verbose_name_plural': 'prioridadesDeTarea'},
        ),
        migrations.AlterModelTable(
            name='estadotarea',
            table='estadosDeTarea',
        ),
        migrations.AlterModelTable(
            name='motivotarea',
            table='motivosDeTarea',
        ),
        migrations.AlterModelTable(
            name='prioridadtarea',
            table='prioridadesDeTarea',
        ),
    ]
