# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-30 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0059_rolenrobotica'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol_en_robotica',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_rol_en_robotica', to='escuelas.RolEnRobotica'),
        ),
    ]
