# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-03 17:27
from __future__ import unicode_literals

from django.db import migrations
from escuelas import models

def cargar_areas_de_robotica(apps, schema_editor):
    area = apps.get_model("escuelas", "AreaDeRobotica")
    area.objects.get_or_create(nombre=u"Troncal")
    area.objects.get_or_create(nombre=u"Matemática")
    area.objects.get_or_create(nombre=u"Prácticas del Lenguaje")
    area.objects.get_or_create(nombre=u"Ciencias Naturales")

class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0061_auto_20180802_1427'),
    ]

    operations = [
        migrations.RunPython(cargar_areas_de_robotica, migrations.RunPython.noop),
    ]
