# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-03 17:46
from __future__ import unicode_literals

from django.db import migrations
from escuelas import models

def cargar_talleres_de_robotica(apps, schema_editor):
    lista_de_talleres = [
        ("Introducción a los campos de conocimiento emergentes. Comprimido.","Troncal"),
        ("Introducción a los campos de conocimiento emergente. Pensamiento computacional y Programación.","Troncal"),
        ("Introducción a los campos de conocimiento emergente. Programación y Robótica.","Troncal"),
        ("Introducción a la Programación.","Troncal"),
        ("Introducción a la robótica educativa.","Troncal"),
        ("¿Programar o ser programado?","Troncal"),
        ("Algoritmos para la resolución de problemas.","Troncal"),
        ("La cultura Digital.","Troncal"),
        ("Introducción al pensamiento computacional. Suma y resta de números naturales.","Matemática"),
        ("Introducción al pensamiento computacional. Multiplicación y división de números naturales.","Matemática"),
        ("Pensamiento computacional. Trayectorias.","Matemática"),
        ("Introducción al pensamiento computacional. Construcción de cuadriláteros.","Matemática"),
        ("Lenguaje de Programación en Scratch. Construcción de cuadrados y rectángulos.","Matemática"),
        ("La programación por bloques referenciada al cálculo de perímetros.","Matemática"),
        ("La programación por bloques referenciada a las unidades de medidas de tiempo.","Matemática"),
        ("La programación por bloques referenciada a la reconstrucción de un entero dada una parte.","Matemática"),
        ("La programación por bloques. Suma y resta de fracciones.","Matemática"),
        ("La robótica. Construcción de cuadrados y rectángulos.","Matemática"),
        ("La robótica. Cálculo de perímetros.","Matemática"),
        ("La robótica. Trayectorias.","Matemática"),
        ("La robótica. Reconstrucción de un entero dada una parte.","Matemática"),
        ("La Programación por bloques. Construcción de cuadrados y trazado de sus diagonales.","Matemática"),
        ("Aprende con la calculadora 1.","Matemática"),
        ("Aprende con la calculadora 2.","Matemática"),
        ("Aprende con la calculadora 3.","Matemática"),
        ("Aprende con la calculadora 4.","Matemática"),
        ("Trayectorias.","Matemática"),
        ("Programando trayectorias.","Matemática"),
        ("Introducción al pensamiento computacional. Construcción de cuadriláteros.","Matemática"),
        ("Programación por bloques. Construcción de cuadriláteros y paralelogramos.","Matemática"),
        ("Programación en Scratch. Construcción de paralelogramos.","Matemática"),
        ("Programación con Scratch. Construcción de la diagonal de los paralelogramos.","Matemática"),
        ("Programando áreas y perímetros.","Matemática"),
        ("Relación entre perímetro, área y lado de un rectángulo en Scratch.","Matemática"),
        ("Diferencias entre variables naturales y racionales.","Matemática"),
        ("Números racionales. Usar fracciones en diferentes clases de problemas.","Matemática"),
        ("Operaciones con fracciones en Scratch.","Matemática"),
        ("Representación gráfica de fracciones.","Matemática"),
        ("El robot hace cuadrados.","Matemática"),
        ("Programando áreas y perímetros con robots.","Matemática"),
        ("El robot nos muestra la relación entre áreas y perímetros.","Matemática"),
        ("Números racionales. Reconstruir un entero con el robot.","Matemática"),
        ("Instrucciones para un robot ¿Tienen lenguaje las computadoras?","Prácticas del Lenguaje"),
        ("Pensamiento computacional referenciado a la elección de un texto literario.","Prácticas del Lenguaje"),
        ("Pensamiento computacional referenciado a la identificación de géneros literarios.","Prácticas del Lenguaje"),
        ("Pensamiento computacional y programación referenciado a la lectura crítica de un cuento breve.","Prácticas del Lenguaje"),
        ("Programación, robótica y literatura. Lecturas complementarias.","Prácticas del Lenguaje"),
        ("Programación: secuencia y procedimiento referenciados a una canción o poesía infantil.","Prácticas del Lenguaje"),
        ("Animación en Scratch de personaje de un texto literario.","Prácticas del Lenguaje"),
        ("Programación y robótica referenciado a la reflexión sobre sustantivos y adjetivos calificativos.","Prácticas del Lenguaje"),
        ("Programación y robótica: antes y después. Tiempos de un relato.","Prácticas del Lenguaje"),
        ("Pensamiento computacional referenciado a la lectura colaborativa.","Prácticas del Lenguaje"),
        ("Programación referenciada a un texto literario.","Prácticas del Lenguaje"),
        ("Programación referenciada a la lectura grupal.","Prácticas del Lenguaje"),
        ("Programación referenciada a la composición de un texto literario.","Prácticas del Lenguaje"),
        ("Programación en Scratch del fragmento de un texto literario.","Prácticas del Lenguaje"),
        ("Programación y robótica, lecturas informativas.","Prácticas del Lenguaje"),
        ("Programación. Secuencia y procedimiento de la ruptura del hilo de un texto literario.","Prácticas del Lenguaje"),
        ("Programación y robótica referenciada a la narrativa transmedia.","Prácticas del Lenguaje"),
        ("Robótica referenciada al tiempo y espacio de un relato.","Prácticas del Lenguaje"),
        ("Los recorridos de un robot. Construcciones preposicionales.","Prácticas del Lenguaje"),
        ("Robótica referenciada a la rotación terrestre.","Ciencias Naturales"),
        ("Robótica referenciada a los cambios de estado.","Ciencias Naturales"),
        ("Robótica referenciada a los cambios de estado.","Ciencias Naturales"),
        ("Pensamiento Computacional referenciado al tiempo atmosférico.","Ciencias Naturales"),
        ("Pensamiento Computacional referenciado a la luz y los objetos.","Ciencias Naturales"),
        ("Pensamiento Computacional referenciado a la rotación terrestre.","Ciencias Naturales"),
        ("Pensamiento Computacional referenciado al tamaño de la tierra.","Ciencias Naturales"),
        ("Introducción a la Programación referenciado a los cambios de estado.","Ciencias Naturales"),
        ("Introducción a la Programación referenciado a la rotación terrestre.","Ciencias Naturales"),
        ("Introducción  a la Programación referenciado a  la presión en el medio acuático.","Ciencias Naturales"),
        ("Robótica referenciada a la interacción entre la luz y los objetos: el color.","Ciencias Naturales"),
        ("Robótica referenciada a la interacción entre los objetos y la luz.","Ciencias Naturales"),
        ("Robótica referenciada a los cambios de estado.","Ciencias Naturales"),
        ("Robótica referenciada al tiempo atmosférico.","Ciencias Naturales"),
        ("Pensamiento Computacional referenciado al tiempo atmosférico.","Ciencias Naturales"),
        ("Pensamiento Computacional referenciado a la luz y los objetos.","Ciencias Naturales"),
        ("Pensamiento Computacional referenciado a los colores, la luz y los objetos..","Ciencias Naturales"),
        ("Pensamiento Computacional referenciado al Sistema Solar y tamaño de los planetas.","Ciencias Naturales"),
        ("Introducción a la Programación referenciada al tamaño de la Tierra.","Ciencias Naturales"),
        ("Introducción a la Programación referenciada al tiempo atmosférico.","Ciencias Naturales"),
        ("La programación referenciada a la interacción entre la luz y los objetos.","Ciencias Naturales")
    ]
    area = apps.get_model("escuelas", "AreaDeRobotica")
    taller_model = apps.get_model("escuelas", "TallerDeRobotica")

    for taller in lista_de_talleres:
        t_area = area.objects.get(nombre=taller[1])
        t, created = taller_model.objects.get_or_create(nombre=taller[0], area=t_area)


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0063_tallerderobotica_area'),
    ]

    operations = [
        migrations.RunPython(cargar_talleres_de_robotica, migrations.RunPython.noop),
    ]
