# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0064_cargar_talleres_de_robotica'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoderobotica',
            name='cerrar_evento',
            field=models.BooleanField(default=False),
        ),
    ]
