# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-06 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0065_eventoderobotica_cerrar_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaderobotica',
            options={'verbose_name_plural': 'Areas (Robotica)'},
        ),
        migrations.AlterModelOptions(
            name='cursoderobotica',
            options={'verbose_name_plural': 'Cursos (Robotica)'},
        ),
        migrations.AlterModelOptions(
            name='eventoderobotica',
            options={'ordering': ('-fecha',), 'verbose_name_plural': 'Eventos (Robotica)'},
        ),
        migrations.AlterModelOptions(
            name='tallerderobotica',
            options={'verbose_name_plural': 'Talleres (Robotica)'},
        ),
    ]
