# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-06 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0066_auto_20180806_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoderobotica',
            name='fecha_fin',
        ),
    ]
