# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-10 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0068_auto_20180810_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjeDeRobotica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ejesDeRobotica',
                'verbose_name_plural': 'Ejes (Robotica)',
            },
        ),
        migrations.AddField(
            model_name='eventoderobotica',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tallerderobotica',
            name='eje',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taller_de_robotica', to='escuelas.EjeDeRobotica'),
        ),
    ]
