# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-10 21:16
from __future__ import unicode_literals

from django.db import migrations

def cargar_ejes_de_robotica(apps, schema_editor):
    eje = apps.get_model("escuelas", "EjeDeRobotica")
    eje.objects.get_or_create(nombre=u"Troncal")
    eje.objects.get_or_create(nombre=u"Programación")
    eje.objects.get_or_create(nombre=u"Robótica")
    eje.objects.get_or_create(nombre=u"Pensamiento computacional")

class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0069_auto_20180810_2010'),
    ]

    operations = [
        migrations.RunPython(cargar_ejes_de_robotica, migrations.RunPython.noop),
    ]
