# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-20 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0070_crear_ejes_de_robotica'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='region',
            field=models.IntegerField(choices=[(0, 'Sin definir'), (1, 'Regi\xf3n 1'), (2, 'Regi\xf3n 2'), (3, 'Regi\xf3n 3')], default=0),
        ),
    ]
