# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0074_auto_20180903_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='identificador',
            field=models.CharField(default=b'', max_length=128),
        ),
    ]
