# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-06 14:07
from __future__ import unicode_literals

from django.db import migrations

def asignar_identificadores(apps, schema_editor):
    aplicacion = apps.get_model("escuelas", "Aplicacion")

    suite = aplicacion.objects.get(nombre=u"SUITE")
    suite.identificador = 'suite'
    suite.save()

    robotica = aplicacion.objects.get(nombre=u"Robótica")
    robotica.identificador = 'robotica'
    robotica.save()

class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0075_aplicacion_identificador'),
    ]

    operations = [
        migrations.RunPython(asignar_identificadores, migrations.RunPython.noop),
    ]
