# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0076_asignar_identificadores_a_las_aplicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoderobotica',
            name='motivo',
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='eventoderobotica',
            name='se_dio_el_taller',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=None, max_length=3, null=True),
        ),
    ]
