# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-17 17:01

# Esta migración asigna el valor Sí al campo se_dio_el_taller, para todos los Talleres
# cerrados al 17/09/2018

from __future__ import unicode_literals

from django.db import migrations

def asignar_si(apps, schema_editor):
    eventoDeRobotica = apps.get_model("escuelas", "EventoDeRobotica")
    eventosCerrados = eventoDeRobotica.objects.filter(cerrar_evento=True)
    for evento in eventosCerrados:
        evento.se_dio_el_taller = "Si"
        evento.save()

class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0077_auto_20180913_1228'),
    ]

    operations = [
        migrations.RunPython(asignar_si, migrations.RunPython.noop),
    ]
