# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0078_asignar_taller_realizado_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='fecha_de_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='perfil_de_ultima_modificacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_modificacion_escuela', to='escuelas.Perfil'),
        ),
    ]
