# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0079_auto_20180927_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_de_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
