from contacto import Contacto
from escuela import Escuela
from evento import Evento
from region import Region
from perfil import Perfil
from tipo_de_financiamiento import TipoDeFinanciamiento
from nivel import Nivel
from tipo_de_gestion import TipoDeGestion
from area import Area
from programa import Programa
from localidad import Localidad
from distrito import Distrito
from experiencia import Experiencia
from cargo import Cargo
from contrato import Contrato
from piso import Piso
from cargo_escolar import CargoEscolar
from tarea import Tarea
from prioridad_de_tarea import PrioridadDeTarea
from motivo_de_tarea import MotivoDeTarea
from estado_de_tarea import EstadoDeTarea
from comentario_de_tarea import ComentarioDeTarea
from categoria_de_evento import CategoriaDeEvento
from estado_de_validacion import EstadoDeValidacion
from validacion import Validacion
from motivo_de_conformacion import MotivoDeConformacion
from comentario_de_validacion import ComentarioDeValidacion
from estado_de_paquete import EstadoDePaquete
from paquete import Paquete
from modalidad import Modalidad
from trabajo import Trabajo
from distribucion_de_paquete import DistribucionDePaquete
